Module(Xenon, 'Command')({
    
    execCommand : function () {},
    queryCommandEnabled : function () {},
    queryCommandIndeterm : function () {},
    queryCommandState : function () {},
    queryCommandValue : function () {},
    
    insert  : function () {},
    remove  : function () {},
    wrap    : function () {},
    unwrap  : function () {},
    style   : function () {},
    unstyle : function () {},
    
    bold : function () {},
    italic : function () {},
    underline : function () {},
    link : function () {},
    copy : function () {},
    cut : function () {},
    paste : function () {},
    backColor : function () {},
    enableInlineTableEditing : function () {},
    enableObjectResizing : function () {},
    fontName : function () {},
    fontSize : function () {},
    foreColor : function () {},
    formatBlock : function () {},
    heading : function () {},
    hiliteColor : function () {},
    increaseFontSize : function () {},
    decreaseFontSize : function () {},
    indent : function () {},
    insertBrOnReturn : function () {},
    insertHorizontalRule : function () {},
    insertHTML : function () {},
    insertImage : function () {},
    insertOrderedList : function () {},
    insertUnorderedList : function () {},
    insertParagraph : function () {},
    italic : function () {},
    justifyCenter : function () {},
    justifyLeft : function () {},
    justifyRight : function () {},
    outdent : function () {},
    redo : function () {},
    removeFormat : function () {},
    selectAll : function () {},
    strikeThrough : function () {},
    subscript : function () {},
    superScript : function () {},
    underline : function () {},
    undo : function () {},
    unlink : function () {},
    styleWithCss : function () {},
    
});